[tool.black]
line-length = 120

[tool.pyright]
reportMissingImports = "none"
reportUnnecessaryTypeIgnoreComment = "warning"
pythonVersion = "3.10"
typeCheckingMode = "basic"

[tool.isort]
profile = "black"
combine_as_imports = true
combine_star = true
line_length = 120
